// This file was generated by Mendix Modeler 7.3.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmodule.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the TestModule module

	public static java.lang.String getYourPhonenumber()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("TestModule.YourPhonenumber");
	}
}