// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bulksms.proxies;

public class InboundSMS
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject inboundSMSMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BulkSMS.InboundSMS";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DATE("DATE"),
		RECIPIENT("RECIPIENT"),
		_ID("_ID"),
		RECEIVER("RECEIVER"),
		MESSAGE("MESSAGE"),
		UDH("UDH"),
		OPERATOR("OPERATOR"),
		BINARY("BINARY"),
		REFERENCE("REFERENCE"),
		SENT("SENT"),
		DCS("DCS"),
		RESERVED1("RESERVED1"),
		RESERVED2("RESERVED2"),
		RESERVED3("RESERVED3"),
		RESERVED4("RESERVED4"),
		RESERVED5("RESERVED5"),
		CUSTOMGROUPING("CUSTOMGROUPING"),
		CUSTOMGROUPING2("CUSTOMGROUPING2"),
		CUSTOMGROUPING3("CUSTOMGROUPING3"),
		SESSIONGUID("SESSIONGUID");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public InboundSMS(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BulkSMS.InboundSMS"));
	}

	protected InboundSMS(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject inboundSMSMendixObject)
	{
		if (inboundSMSMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BulkSMS.InboundSMS", inboundSMSMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BulkSMS.InboundSMS");

		this.inboundSMSMendixObject = inboundSMSMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'InboundSMS.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static bulksms.proxies.InboundSMS initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return bulksms.proxies.InboundSMS.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static bulksms.proxies.InboundSMS initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new bulksms.proxies.InboundSMS(context, mendixObject);
	}

	public static bulksms.proxies.InboundSMS load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return bulksms.proxies.InboundSMS.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DATE
	 */
	public final java.lang.String getDATE()
	{
		return getDATE(getContext());
	}

	/**
	 * @param context
	 * @return value of DATE
	 */
	public final java.lang.String getDATE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DATE.toString());
	}

	/**
	 * Set value of DATE
	 * @param date
	 */
	public final void setDATE(java.lang.String date)
	{
		setDATE(getContext(), date);
	}

	/**
	 * Set value of DATE
	 * @param context
	 * @param date
	 */
	public final void setDATE(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String date)
	{
		getMendixObject().setValue(context, MemberNames.DATE.toString(), date);
	}

	/**
	 * @return value of RECIPIENT
	 */
	public final java.lang.String getRECIPIENT()
	{
		return getRECIPIENT(getContext());
	}

	/**
	 * @param context
	 * @return value of RECIPIENT
	 */
	public final java.lang.String getRECIPIENT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RECIPIENT.toString());
	}

	/**
	 * Set value of RECIPIENT
	 * @param recipient
	 */
	public final void setRECIPIENT(java.lang.String recipient)
	{
		setRECIPIENT(getContext(), recipient);
	}

	/**
	 * Set value of RECIPIENT
	 * @param context
	 * @param recipient
	 */
	public final void setRECIPIENT(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String recipient)
	{
		getMendixObject().setValue(context, MemberNames.RECIPIENT.toString(), recipient);
	}

	/**
	 * @return value of _ID
	 */
	public final java.lang.Integer get_ID()
	{
		return get_ID(getContext());
	}

	/**
	 * @param context
	 * @return value of _ID
	 */
	public final java.lang.Integer get_ID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames._ID.toString());
	}

	/**
	 * Set value of _ID
	 * @param _id
	 */
	public final void set_ID(java.lang.Integer _id)
	{
		set_ID(getContext(), _id);
	}

	/**
	 * Set value of _ID
	 * @param context
	 * @param _id
	 */
	public final void set_ID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer _id)
	{
		getMendixObject().setValue(context, MemberNames._ID.toString(), _id);
	}

	/**
	 * @return value of RECEIVER
	 */
	public final java.lang.Long getRECEIVER()
	{
		return getRECEIVER(getContext());
	}

	/**
	 * @param context
	 * @return value of RECEIVER
	 */
	public final java.lang.Long getRECEIVER(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.RECEIVER.toString());
	}

	/**
	 * Set value of RECEIVER
	 * @param receiver
	 */
	public final void setRECEIVER(java.lang.Long receiver)
	{
		setRECEIVER(getContext(), receiver);
	}

	/**
	 * Set value of RECEIVER
	 * @param context
	 * @param receiver
	 */
	public final void setRECEIVER(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long receiver)
	{
		getMendixObject().setValue(context, MemberNames.RECEIVER.toString(), receiver);
	}

	/**
	 * @return value of MESSAGE
	 */
	public final java.lang.String getMESSAGE()
	{
		return getMESSAGE(getContext());
	}

	/**
	 * @param context
	 * @return value of MESSAGE
	 */
	public final java.lang.String getMESSAGE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MESSAGE.toString());
	}

	/**
	 * Set value of MESSAGE
	 * @param message
	 */
	public final void setMESSAGE(java.lang.String message)
	{
		setMESSAGE(getContext(), message);
	}

	/**
	 * Set value of MESSAGE
	 * @param context
	 * @param message
	 */
	public final void setMESSAGE(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String message)
	{
		getMendixObject().setValue(context, MemberNames.MESSAGE.toString(), message);
	}

	/**
	 * @return value of UDH
	 */
	public final java.lang.String getUDH()
	{
		return getUDH(getContext());
	}

	/**
	 * @param context
	 * @return value of UDH
	 */
	public final java.lang.String getUDH(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UDH.toString());
	}

	/**
	 * Set value of UDH
	 * @param udh
	 */
	public final void setUDH(java.lang.String udh)
	{
		setUDH(getContext(), udh);
	}

	/**
	 * Set value of UDH
	 * @param context
	 * @param udh
	 */
	public final void setUDH(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String udh)
	{
		getMendixObject().setValue(context, MemberNames.UDH.toString(), udh);
	}

	/**
	 * @return value of OPERATOR
	 */
	public final java.lang.String getOPERATOR()
	{
		return getOPERATOR(getContext());
	}

	/**
	 * @param context
	 * @return value of OPERATOR
	 */
	public final java.lang.String getOPERATOR(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OPERATOR.toString());
	}

	/**
	 * Set value of OPERATOR
	 * @param operator
	 */
	public final void setOPERATOR(java.lang.String operator)
	{
		setOPERATOR(getContext(), operator);
	}

	/**
	 * Set value of OPERATOR
	 * @param context
	 * @param operator
	 */
	public final void setOPERATOR(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String operator)
	{
		getMendixObject().setValue(context, MemberNames.OPERATOR.toString(), operator);
	}

	/**
	 * @return value of BINARY
	 */
	public final java.lang.String getBINARY()
	{
		return getBINARY(getContext());
	}

	/**
	 * @param context
	 * @return value of BINARY
	 */
	public final java.lang.String getBINARY(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BINARY.toString());
	}

	/**
	 * Set value of BINARY
	 * @param binary
	 */
	public final void setBINARY(java.lang.String binary)
	{
		setBINARY(getContext(), binary);
	}

	/**
	 * Set value of BINARY
	 * @param context
	 * @param binary
	 */
	public final void setBINARY(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String binary)
	{
		getMendixObject().setValue(context, MemberNames.BINARY.toString(), binary);
	}

	/**
	 * @return value of REFERENCE
	 */
	public final java.lang.String getREFERENCE()
	{
		return getREFERENCE(getContext());
	}

	/**
	 * @param context
	 * @return value of REFERENCE
	 */
	public final java.lang.String getREFERENCE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.REFERENCE.toString());
	}

	/**
	 * Set value of REFERENCE
	 * @param reference
	 */
	public final void setREFERENCE(java.lang.String reference)
	{
		setREFERENCE(getContext(), reference);
	}

	/**
	 * Set value of REFERENCE
	 * @param context
	 * @param reference
	 */
	public final void setREFERENCE(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reference)
	{
		getMendixObject().setValue(context, MemberNames.REFERENCE.toString(), reference);
	}

	/**
	 * @return value of SENT
	 */
	public final java.util.Date getSENT()
	{
		return getSENT(getContext());
	}

	/**
	 * @param context
	 * @return value of SENT
	 */
	public final java.util.Date getSENT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.SENT.toString());
	}

	/**
	 * Set value of SENT
	 * @param sent
	 */
	public final void setSENT(java.util.Date sent)
	{
		setSENT(getContext(), sent);
	}

	/**
	 * Set value of SENT
	 * @param context
	 * @param sent
	 */
	public final void setSENT(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date sent)
	{
		getMendixObject().setValue(context, MemberNames.SENT.toString(), sent);
	}

	/**
	 * @return value of DCS
	 */
	public final java.lang.String getDCS()
	{
		return getDCS(getContext());
	}

	/**
	 * @param context
	 * @return value of DCS
	 */
	public final java.lang.String getDCS(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DCS.toString());
	}

	/**
	 * Set value of DCS
	 * @param dcs
	 */
	public final void setDCS(java.lang.String dcs)
	{
		setDCS(getContext(), dcs);
	}

	/**
	 * Set value of DCS
	 * @param context
	 * @param dcs
	 */
	public final void setDCS(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dcs)
	{
		getMendixObject().setValue(context, MemberNames.DCS.toString(), dcs);
	}

	/**
	 * @return value of RESERVED1
	 */
	public final java.lang.String getRESERVED1()
	{
		return getRESERVED1(getContext());
	}

	/**
	 * @param context
	 * @return value of RESERVED1
	 */
	public final java.lang.String getRESERVED1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RESERVED1.toString());
	}

	/**
	 * Set value of RESERVED1
	 * @param reserved1
	 */
	public final void setRESERVED1(java.lang.String reserved1)
	{
		setRESERVED1(getContext(), reserved1);
	}

	/**
	 * Set value of RESERVED1
	 * @param context
	 * @param reserved1
	 */
	public final void setRESERVED1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reserved1)
	{
		getMendixObject().setValue(context, MemberNames.RESERVED1.toString(), reserved1);
	}

	/**
	 * @return value of RESERVED2
	 */
	public final java.lang.String getRESERVED2()
	{
		return getRESERVED2(getContext());
	}

	/**
	 * @param context
	 * @return value of RESERVED2
	 */
	public final java.lang.String getRESERVED2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RESERVED2.toString());
	}

	/**
	 * Set value of RESERVED2
	 * @param reserved2
	 */
	public final void setRESERVED2(java.lang.String reserved2)
	{
		setRESERVED2(getContext(), reserved2);
	}

	/**
	 * Set value of RESERVED2
	 * @param context
	 * @param reserved2
	 */
	public final void setRESERVED2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reserved2)
	{
		getMendixObject().setValue(context, MemberNames.RESERVED2.toString(), reserved2);
	}

	/**
	 * @return value of RESERVED3
	 */
	public final java.lang.String getRESERVED3()
	{
		return getRESERVED3(getContext());
	}

	/**
	 * @param context
	 * @return value of RESERVED3
	 */
	public final java.lang.String getRESERVED3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RESERVED3.toString());
	}

	/**
	 * Set value of RESERVED3
	 * @param reserved3
	 */
	public final void setRESERVED3(java.lang.String reserved3)
	{
		setRESERVED3(getContext(), reserved3);
	}

	/**
	 * Set value of RESERVED3
	 * @param context
	 * @param reserved3
	 */
	public final void setRESERVED3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reserved3)
	{
		getMendixObject().setValue(context, MemberNames.RESERVED3.toString(), reserved3);
	}

	/**
	 * @return value of RESERVED4
	 */
	public final java.lang.String getRESERVED4()
	{
		return getRESERVED4(getContext());
	}

	/**
	 * @param context
	 * @return value of RESERVED4
	 */
	public final java.lang.String getRESERVED4(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RESERVED4.toString());
	}

	/**
	 * Set value of RESERVED4
	 * @param reserved4
	 */
	public final void setRESERVED4(java.lang.String reserved4)
	{
		setRESERVED4(getContext(), reserved4);
	}

	/**
	 * Set value of RESERVED4
	 * @param context
	 * @param reserved4
	 */
	public final void setRESERVED4(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reserved4)
	{
		getMendixObject().setValue(context, MemberNames.RESERVED4.toString(), reserved4);
	}

	/**
	 * @return value of RESERVED5
	 */
	public final java.lang.String getRESERVED5()
	{
		return getRESERVED5(getContext());
	}

	/**
	 * @param context
	 * @return value of RESERVED5
	 */
	public final java.lang.String getRESERVED5(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RESERVED5.toString());
	}

	/**
	 * Set value of RESERVED5
	 * @param reserved5
	 */
	public final void setRESERVED5(java.lang.String reserved5)
	{
		setRESERVED5(getContext(), reserved5);
	}

	/**
	 * Set value of RESERVED5
	 * @param context
	 * @param reserved5
	 */
	public final void setRESERVED5(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reserved5)
	{
		getMendixObject().setValue(context, MemberNames.RESERVED5.toString(), reserved5);
	}

	/**
	 * @return value of CUSTOMGROUPING
	 */
	public final java.lang.String getCUSTOMGROUPING()
	{
		return getCUSTOMGROUPING(getContext());
	}

	/**
	 * @param context
	 * @return value of CUSTOMGROUPING
	 */
	public final java.lang.String getCUSTOMGROUPING(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CUSTOMGROUPING.toString());
	}

	/**
	 * Set value of CUSTOMGROUPING
	 * @param customgrouping
	 */
	public final void setCUSTOMGROUPING(java.lang.String customgrouping)
	{
		setCUSTOMGROUPING(getContext(), customgrouping);
	}

	/**
	 * Set value of CUSTOMGROUPING
	 * @param context
	 * @param customgrouping
	 */
	public final void setCUSTOMGROUPING(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customgrouping)
	{
		getMendixObject().setValue(context, MemberNames.CUSTOMGROUPING.toString(), customgrouping);
	}

	/**
	 * @return value of CUSTOMGROUPING2
	 */
	public final java.lang.String getCUSTOMGROUPING2()
	{
		return getCUSTOMGROUPING2(getContext());
	}

	/**
	 * @param context
	 * @return value of CUSTOMGROUPING2
	 */
	public final java.lang.String getCUSTOMGROUPING2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CUSTOMGROUPING2.toString());
	}

	/**
	 * Set value of CUSTOMGROUPING2
	 * @param customgrouping2
	 */
	public final void setCUSTOMGROUPING2(java.lang.String customgrouping2)
	{
		setCUSTOMGROUPING2(getContext(), customgrouping2);
	}

	/**
	 * Set value of CUSTOMGROUPING2
	 * @param context
	 * @param customgrouping2
	 */
	public final void setCUSTOMGROUPING2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customgrouping2)
	{
		getMendixObject().setValue(context, MemberNames.CUSTOMGROUPING2.toString(), customgrouping2);
	}

	/**
	 * @return value of CUSTOMGROUPING3
	 */
	public final java.lang.String getCUSTOMGROUPING3()
	{
		return getCUSTOMGROUPING3(getContext());
	}

	/**
	 * @param context
	 * @return value of CUSTOMGROUPING3
	 */
	public final java.lang.String getCUSTOMGROUPING3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CUSTOMGROUPING3.toString());
	}

	/**
	 * Set value of CUSTOMGROUPING3
	 * @param customgrouping3
	 */
	public final void setCUSTOMGROUPING3(java.lang.String customgrouping3)
	{
		setCUSTOMGROUPING3(getContext(), customgrouping3);
	}

	/**
	 * Set value of CUSTOMGROUPING3
	 * @param context
	 * @param customgrouping3
	 */
	public final void setCUSTOMGROUPING3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customgrouping3)
	{
		getMendixObject().setValue(context, MemberNames.CUSTOMGROUPING3.toString(), customgrouping3);
	}

	/**
	 * @return value of SESSIONGUID
	 */
	public final java.lang.String getSESSIONGUID()
	{
		return getSESSIONGUID(getContext());
	}

	/**
	 * @param context
	 * @return value of SESSIONGUID
	 */
	public final java.lang.String getSESSIONGUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SESSIONGUID.toString());
	}

	/**
	 * Set value of SESSIONGUID
	 * @param sessionguid
	 */
	public final void setSESSIONGUID(java.lang.String sessionguid)
	{
		setSESSIONGUID(getContext(), sessionguid);
	}

	/**
	 * Set value of SESSIONGUID
	 * @param context
	 * @param sessionguid
	 */
	public final void setSESSIONGUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sessionguid)
	{
		getMendixObject().setValue(context, MemberNames.SESSIONGUID.toString(), sessionguid);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return inboundSMSMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final bulksms.proxies.InboundSMS that = (bulksms.proxies.InboundSMS) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BulkSMS.InboundSMS";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
