// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bulksms.proxies;

public class MessageResponse
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject messageResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BulkSMS.MessageResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		To("To"),
		Reference("Reference"),
		status("status"),
		parts("parts"),
		messageDetails("messageDetails"),
		messageErrorCode("messageErrorCode"),
		MessageResponse_Response("BulkSMS.MessageResponse_Response");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MessageResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BulkSMS.MessageResponse"));
	}

	protected MessageResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject messageResponseMendixObject)
	{
		if (messageResponseMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BulkSMS.MessageResponse", messageResponseMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BulkSMS.MessageResponse");

		this.messageResponseMendixObject = messageResponseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MessageResponse.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static bulksms.proxies.MessageResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return bulksms.proxies.MessageResponse.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static bulksms.proxies.MessageResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new bulksms.proxies.MessageResponse(context, mendixObject);
	}

	public static bulksms.proxies.MessageResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return bulksms.proxies.MessageResponse.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of To
	 */
	public final java.lang.String getTo()
	{
		return getTo(getContext());
	}

	/**
	 * @param context
	 * @return value of To
	 */
	public final java.lang.String getTo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.To.toString());
	}

	/**
	 * Set value of To
	 * @param to
	 */
	public final void setTo(java.lang.String to)
	{
		setTo(getContext(), to);
	}

	/**
	 * Set value of To
	 * @param context
	 * @param to
	 */
	public final void setTo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String to)
	{
		getMendixObject().setValue(context, MemberNames.To.toString(), to);
	}

	/**
	 * @return value of Reference
	 */
	public final java.lang.String getReference()
	{
		return getReference(getContext());
	}

	/**
	 * @param context
	 * @return value of Reference
	 */
	public final java.lang.String getReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Reference.toString());
	}

	/**
	 * Set value of Reference
	 * @param reference
	 */
	public final void setReference(java.lang.String reference)
	{
		setReference(getContext(), reference);
	}

	/**
	 * Set value of Reference
	 * @param context
	 * @param reference
	 */
	public final void setReference(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reference)
	{
		getMendixObject().setValue(context, MemberNames.Reference.toString(), reference);
	}

	/**
	 * @return value of status
	 */
	public final java.lang.String getstatus()
	{
		return getstatus(getContext());
	}

	/**
	 * @param context
	 * @return value of status
	 */
	public final java.lang.String getstatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.status.toString());
	}

	/**
	 * Set value of status
	 * @param status
	 */
	public final void setstatus(java.lang.String status)
	{
		setstatus(getContext(), status);
	}

	/**
	 * Set value of status
	 * @param context
	 * @param status
	 */
	public final void setstatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.status.toString(), status);
	}

	/**
	 * @return value of parts
	 */
	public final java.lang.Integer getparts()
	{
		return getparts(getContext());
	}

	/**
	 * @param context
	 * @return value of parts
	 */
	public final java.lang.Integer getparts(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.parts.toString());
	}

	/**
	 * Set value of parts
	 * @param parts
	 */
	public final void setparts(java.lang.Integer parts)
	{
		setparts(getContext(), parts);
	}

	/**
	 * Set value of parts
	 * @param context
	 * @param parts
	 */
	public final void setparts(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer parts)
	{
		getMendixObject().setValue(context, MemberNames.parts.toString(), parts);
	}

	/**
	 * @return value of messageDetails
	 */
	public final java.lang.String getmessageDetails()
	{
		return getmessageDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of messageDetails
	 */
	public final java.lang.String getmessageDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.messageDetails.toString());
	}

	/**
	 * Set value of messageDetails
	 * @param messagedetails
	 */
	public final void setmessageDetails(java.lang.String messagedetails)
	{
		setmessageDetails(getContext(), messagedetails);
	}

	/**
	 * Set value of messageDetails
	 * @param context
	 * @param messagedetails
	 */
	public final void setmessageDetails(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String messagedetails)
	{
		getMendixObject().setValue(context, MemberNames.messageDetails.toString(), messagedetails);
	}

	/**
	 * @return value of messageErrorCode
	 */
	public final java.lang.Integer getmessageErrorCode()
	{
		return getmessageErrorCode(getContext());
	}

	/**
	 * @param context
	 * @return value of messageErrorCode
	 */
	public final java.lang.Integer getmessageErrorCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.messageErrorCode.toString());
	}

	/**
	 * Set value of messageErrorCode
	 * @param messageerrorcode
	 */
	public final void setmessageErrorCode(java.lang.Integer messageerrorcode)
	{
		setmessageErrorCode(getContext(), messageerrorcode);
	}

	/**
	 * Set value of messageErrorCode
	 * @param context
	 * @param messageerrorcode
	 */
	public final void setmessageErrorCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer messageerrorcode)
	{
		getMendixObject().setValue(context, MemberNames.messageErrorCode.toString(), messageerrorcode);
	}

	/**
	 * @return value of MessageResponse_Response
	 */
	public final bulksms.proxies.Response getMessageResponse_Response() throws com.mendix.core.CoreException
	{
		return getMessageResponse_Response(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageResponse_Response
	 */
	public final bulksms.proxies.Response getMessageResponse_Response(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		bulksms.proxies.Response result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MessageResponse_Response.toString());
		if (identifier != null)
			result = bulksms.proxies.Response.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MessageResponse_Response
	 * @param messageresponse_response
	 */
	public final void setMessageResponse_Response(bulksms.proxies.Response messageresponse_response)
	{
		setMessageResponse_Response(getContext(), messageresponse_response);
	}

	/**
	 * Set value of MessageResponse_Response
	 * @param context
	 * @param messageresponse_response
	 */
	public final void setMessageResponse_Response(com.mendix.systemwideinterfaces.core.IContext context, bulksms.proxies.Response messageresponse_response)
	{
		if (messageresponse_response == null)
			getMendixObject().setValue(context, MemberNames.MessageResponse_Response.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MessageResponse_Response.toString(), messageresponse_response.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return messageResponseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final bulksms.proxies.MessageResponse that = (bulksms.proxies.MessageResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BulkSMS.MessageResponse";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
