// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bulksms.proxies;

public class Message
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject messageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BulkSMS.Message";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		From("From"),
		Reference("Reference"),
		MinimumNumberOfMessageParts("MinimumNumberOfMessageParts"),
		MaximumNumberOfMessageParts("MaximumNumberOfMessageParts"),
		EncodingType("EncodingType"),
		Body("Body"),
		CustomGrouping("CustomGrouping"),
		Message_Message("BulkSMS.Message_Message"),
		Message_Request("BulkSMS.Message_Request");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Message(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BulkSMS.Message"));
	}

	protected Message(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject messageMendixObject)
	{
		if (messageMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BulkSMS.Message", messageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BulkSMS.Message");

		this.messageMendixObject = messageMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Message.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static bulksms.proxies.Message initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return bulksms.proxies.Message.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static bulksms.proxies.Message initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new bulksms.proxies.Message(context, mendixObject);
	}

	public static bulksms.proxies.Message load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return bulksms.proxies.Message.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of From
	 */
	public final java.lang.String getFrom()
	{
		return getFrom(getContext());
	}

	/**
	 * @param context
	 * @return value of From
	 */
	public final java.lang.String getFrom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.From.toString());
	}

	/**
	 * Set value of From
	 * @param from
	 */
	public final void setFrom(java.lang.String from)
	{
		setFrom(getContext(), from);
	}

	/**
	 * Set value of From
	 * @param context
	 * @param from
	 */
	public final void setFrom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String from)
	{
		getMendixObject().setValue(context, MemberNames.From.toString(), from);
	}

	/**
	 * @return value of Reference
	 */
	public final java.lang.String getReference()
	{
		return getReference(getContext());
	}

	/**
	 * @param context
	 * @return value of Reference
	 */
	public final java.lang.String getReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Reference.toString());
	}

	/**
	 * Set value of Reference
	 * @param reference
	 */
	public final void setReference(java.lang.String reference)
	{
		setReference(getContext(), reference);
	}

	/**
	 * Set value of Reference
	 * @param context
	 * @param reference
	 */
	public final void setReference(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reference)
	{
		getMendixObject().setValue(context, MemberNames.Reference.toString(), reference);
	}

	/**
	 * @return value of MinimumNumberOfMessageParts
	 */
	public final java.lang.Integer getMinimumNumberOfMessageParts()
	{
		return getMinimumNumberOfMessageParts(getContext());
	}

	/**
	 * @param context
	 * @return value of MinimumNumberOfMessageParts
	 */
	public final java.lang.Integer getMinimumNumberOfMessageParts(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MinimumNumberOfMessageParts.toString());
	}

	/**
	 * Set value of MinimumNumberOfMessageParts
	 * @param minimumnumberofmessageparts
	 */
	public final void setMinimumNumberOfMessageParts(java.lang.Integer minimumnumberofmessageparts)
	{
		setMinimumNumberOfMessageParts(getContext(), minimumnumberofmessageparts);
	}

	/**
	 * Set value of MinimumNumberOfMessageParts
	 * @param context
	 * @param minimumnumberofmessageparts
	 */
	public final void setMinimumNumberOfMessageParts(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer minimumnumberofmessageparts)
	{
		getMendixObject().setValue(context, MemberNames.MinimumNumberOfMessageParts.toString(), minimumnumberofmessageparts);
	}

	/**
	 * @return value of MaximumNumberOfMessageParts
	 */
	public final java.lang.Integer getMaximumNumberOfMessageParts()
	{
		return getMaximumNumberOfMessageParts(getContext());
	}

	/**
	 * @param context
	 * @return value of MaximumNumberOfMessageParts
	 */
	public final java.lang.Integer getMaximumNumberOfMessageParts(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaximumNumberOfMessageParts.toString());
	}

	/**
	 * Set value of MaximumNumberOfMessageParts
	 * @param maximumnumberofmessageparts
	 */
	public final void setMaximumNumberOfMessageParts(java.lang.Integer maximumnumberofmessageparts)
	{
		setMaximumNumberOfMessageParts(getContext(), maximumnumberofmessageparts);
	}

	/**
	 * Set value of MaximumNumberOfMessageParts
	 * @param context
	 * @param maximumnumberofmessageparts
	 */
	public final void setMaximumNumberOfMessageParts(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maximumnumberofmessageparts)
	{
		getMendixObject().setValue(context, MemberNames.MaximumNumberOfMessageParts.toString(), maximumnumberofmessageparts);
	}

	/**
	 * @return value of EncodingType
	 */
	public final java.lang.String getEncodingType()
	{
		return getEncodingType(getContext());
	}

	/**
	 * @param context
	 * @return value of EncodingType
	 */
	public final java.lang.String getEncodingType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EncodingType.toString());
	}

	/**
	 * Set value of EncodingType
	 * @param encodingtype
	 */
	public final void setEncodingType(java.lang.String encodingtype)
	{
		setEncodingType(getContext(), encodingtype);
	}

	/**
	 * Set value of EncodingType
	 * @param context
	 * @param encodingtype
	 */
	public final void setEncodingType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String encodingtype)
	{
		getMendixObject().setValue(context, MemberNames.EncodingType.toString(), encodingtype);
	}

	/**
	 * @return value of Body
	 */
	public final java.lang.String getBody()
	{
		return getBody(getContext());
	}

	/**
	 * @param context
	 * @return value of Body
	 */
	public final java.lang.String getBody(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Body.toString());
	}

	/**
	 * Set value of Body
	 * @param body
	 */
	public final void setBody(java.lang.String body)
	{
		setBody(getContext(), body);
	}

	/**
	 * Set value of Body
	 * @param context
	 * @param body
	 */
	public final void setBody(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String body)
	{
		getMendixObject().setValue(context, MemberNames.Body.toString(), body);
	}

	/**
	 * @return value of CustomGrouping
	 */
	public final java.lang.String getCustomGrouping()
	{
		return getCustomGrouping(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomGrouping
	 */
	public final java.lang.String getCustomGrouping(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CustomGrouping.toString());
	}

	/**
	 * Set value of CustomGrouping
	 * @param customgrouping
	 */
	public final void setCustomGrouping(java.lang.String customgrouping)
	{
		setCustomGrouping(getContext(), customgrouping);
	}

	/**
	 * Set value of CustomGrouping
	 * @param context
	 * @param customgrouping
	 */
	public final void setCustomGrouping(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customgrouping)
	{
		getMendixObject().setValue(context, MemberNames.CustomGrouping.toString(), customgrouping);
	}

	/**
	 * @return value of Message_Message
	 */
	public final bulksms.proxies.Message getMessage_Message() throws com.mendix.core.CoreException
	{
		return getMessage_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Message_Message
	 */
	public final bulksms.proxies.Message getMessage_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		bulksms.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Message_Message.toString());
		if (identifier != null)
			result = bulksms.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Message_Message
	 * @param message_message
	 */
	public final void setMessage_Message(bulksms.proxies.Message message_message)
	{
		setMessage_Message(getContext(), message_message);
	}

	/**
	 * Set value of Message_Message
	 * @param context
	 * @param message_message
	 */
	public final void setMessage_Message(com.mendix.systemwideinterfaces.core.IContext context, bulksms.proxies.Message message_message)
	{
		if (message_message == null)
			getMendixObject().setValue(context, MemberNames.Message_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Message_Message.toString(), message_message.getMendixObject().getId());
	}

	/**
	 * @return value of Message_Request
	 */
	public final bulksms.proxies.Request getMessage_Request() throws com.mendix.core.CoreException
	{
		return getMessage_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of Message_Request
	 */
	public final bulksms.proxies.Request getMessage_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		bulksms.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Message_Request.toString());
		if (identifier != null)
			result = bulksms.proxies.Request.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Message_Request
	 * @param message_request
	 */
	public final void setMessage_Request(bulksms.proxies.Request message_request)
	{
		setMessage_Request(getContext(), message_request);
	}

	/**
	 * Set value of Message_Request
	 * @param context
	 * @param message_request
	 */
	public final void setMessage_Request(com.mendix.systemwideinterfaces.core.IContext context, bulksms.proxies.Request message_request)
	{
		if (message_request == null)
			getMendixObject().setValue(context, MemberNames.Message_Request.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Message_Request.toString(), message_request.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return messageMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final bulksms.proxies.Message that = (bulksms.proxies.Message) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BulkSMS.Message";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
