// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bulksms.proxies;

public class Msg
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject msgMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BulkSMS.Msg";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Received("Received"),
		To("To"),
		Reference("Reference"),
		Operator("Operator"),
		Status_Msg("BulkSMS.Status_Msg");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Msg(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BulkSMS.Msg"));
	}

	protected Msg(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject msgMendixObject)
	{
		if (msgMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BulkSMS.Msg", msgMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BulkSMS.Msg");

		this.msgMendixObject = msgMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Msg.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static bulksms.proxies.Msg initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return bulksms.proxies.Msg.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static bulksms.proxies.Msg initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new bulksms.proxies.Msg(context, mendixObject);
	}

	public static bulksms.proxies.Msg load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return bulksms.proxies.Msg.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Received
	 */
	public final java.lang.String getReceived()
	{
		return getReceived(getContext());
	}

	/**
	 * @param context
	 * @return value of Received
	 */
	public final java.lang.String getReceived(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Received.toString());
	}

	/**
	 * Set value of Received
	 * @param received
	 */
	public final void setReceived(java.lang.String received)
	{
		setReceived(getContext(), received);
	}

	/**
	 * Set value of Received
	 * @param context
	 * @param received
	 */
	public final void setReceived(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String received)
	{
		getMendixObject().setValue(context, MemberNames.Received.toString(), received);
	}

	/**
	 * @return value of To
	 */
	public final java.lang.String getTo()
	{
		return getTo(getContext());
	}

	/**
	 * @param context
	 * @return value of To
	 */
	public final java.lang.String getTo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.To.toString());
	}

	/**
	 * Set value of To
	 * @param to
	 */
	public final void setTo(java.lang.String to)
	{
		setTo(getContext(), to);
	}

	/**
	 * Set value of To
	 * @param context
	 * @param to
	 */
	public final void setTo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String to)
	{
		getMendixObject().setValue(context, MemberNames.To.toString(), to);
	}

	/**
	 * @return value of Reference
	 */
	public final java.lang.String getReference()
	{
		return getReference(getContext());
	}

	/**
	 * @param context
	 * @return value of Reference
	 */
	public final java.lang.String getReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Reference.toString());
	}

	/**
	 * Set value of Reference
	 * @param reference
	 */
	public final void setReference(java.lang.String reference)
	{
		setReference(getContext(), reference);
	}

	/**
	 * Set value of Reference
	 * @param context
	 * @param reference
	 */
	public final void setReference(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reference)
	{
		getMendixObject().setValue(context, MemberNames.Reference.toString(), reference);
	}

	/**
	 * @return value of Operator
	 */
	public final java.lang.String getOperator()
	{
		return getOperator(getContext());
	}

	/**
	 * @param context
	 * @return value of Operator
	 */
	public final java.lang.String getOperator(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Operator.toString());
	}

	/**
	 * Set value of Operator
	 * @param operator
	 */
	public final void setOperator(java.lang.String operator)
	{
		setOperator(getContext(), operator);
	}

	/**
	 * Set value of Operator
	 * @param context
	 * @param operator
	 */
	public final void setOperator(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String operator)
	{
		getMendixObject().setValue(context, MemberNames.Operator.toString(), operator);
	}

	/**
	 * @return value of Status_Msg
	 */
	public final bulksms.proxies.Status getStatus_Msg() throws com.mendix.core.CoreException
	{
		return getStatus_Msg(getContext());
	}

	/**
	 * @param context
	 * @return value of Status_Msg
	 */
	public final bulksms.proxies.Status getStatus_Msg(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		bulksms.proxies.Status result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Status_Msg.toString());
		if (identifier != null)
			result = bulksms.proxies.Status.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Status_Msg
	 * @param status_msg
	 */
	public final void setStatus_Msg(bulksms.proxies.Status status_msg)
	{
		setStatus_Msg(getContext(), status_msg);
	}

	/**
	 * Set value of Status_Msg
	 * @param context
	 * @param status_msg
	 */
	public final void setStatus_Msg(com.mendix.systemwideinterfaces.core.IContext context, bulksms.proxies.Status status_msg)
	{
		if (status_msg == null)
			getMendixObject().setValue(context, MemberNames.Status_Msg.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Status_Msg.toString(), status_msg.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return msgMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final bulksms.proxies.Msg that = (bulksms.proxies.Msg) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BulkSMS.Msg";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
