// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bulksms.proxies;

public class Response
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject responseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BulkSMS.Response";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		details("details"),
		errorCode("errorCode");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Response(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BulkSMS.Response"));
	}

	protected Response(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject responseMendixObject)
	{
		if (responseMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BulkSMS.Response", responseMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BulkSMS.Response");

		this.responseMendixObject = responseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Response.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static bulksms.proxies.Response initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return bulksms.proxies.Response.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static bulksms.proxies.Response initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new bulksms.proxies.Response(context, mendixObject);
	}

	public static bulksms.proxies.Response load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return bulksms.proxies.Response.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of details
	 */
	public final java.lang.String getdetails()
	{
		return getdetails(getContext());
	}

	/**
	 * @param context
	 * @return value of details
	 */
	public final java.lang.String getdetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.details.toString());
	}

	/**
	 * Set value of details
	 * @param details
	 */
	public final void setdetails(java.lang.String details)
	{
		setdetails(getContext(), details);
	}

	/**
	 * Set value of details
	 * @param context
	 * @param details
	 */
	public final void setdetails(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String details)
	{
		getMendixObject().setValue(context, MemberNames.details.toString(), details);
	}

	/**
	 * @return value of errorCode
	 */
	public final java.lang.Integer geterrorCode()
	{
		return geterrorCode(getContext());
	}

	/**
	 * @param context
	 * @return value of errorCode
	 */
	public final java.lang.Integer geterrorCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.errorCode.toString());
	}

	/**
	 * Set value of errorCode
	 * @param errorcode
	 */
	public final void seterrorCode(java.lang.Integer errorcode)
	{
		seterrorCode(getContext(), errorcode);
	}

	/**
	 * Set value of errorCode
	 * @param context
	 * @param errorcode
	 */
	public final void seterrorCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer errorcode)
	{
		getMendixObject().setValue(context, MemberNames.errorCode.toString(), errorcode);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return responseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final bulksms.proxies.Response that = (bulksms.proxies.Response) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BulkSMS.Response";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
