// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bulksms.proxies;

public class StatusReportForSMS
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject statusReportForSMSMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BulkSMS.StatusReportForSMS";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CreatedDateByCM("CreatedDateByCM"),
		SentDate("SentDate"),
		PhoneNumber("PhoneNumber"),
		Reference("Reference"),
		ErrorMessage("ErrorMessage"),
		StatusCode("StatusCode"),
		StatusDescription("StatusDescription"),
		ExternalStatusDescription("ExternalStatusDescription"),
		ExternalId("ExternalId"),
		Operator("Operator"),
		Recipient("Recipient"),
		IsSucces("IsSucces");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public StatusReportForSMS(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BulkSMS.StatusReportForSMS"));
	}

	protected StatusReportForSMS(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject statusReportForSMSMendixObject)
	{
		if (statusReportForSMSMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BulkSMS.StatusReportForSMS", statusReportForSMSMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BulkSMS.StatusReportForSMS");

		this.statusReportForSMSMendixObject = statusReportForSMSMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'StatusReportForSMS.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static bulksms.proxies.StatusReportForSMS initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return bulksms.proxies.StatusReportForSMS.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static bulksms.proxies.StatusReportForSMS initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new bulksms.proxies.StatusReportForSMS(context, mendixObject);
	}

	public static bulksms.proxies.StatusReportForSMS load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return bulksms.proxies.StatusReportForSMS.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CreatedDateByCM
	 */
	public final java.util.Date getCreatedDateByCM()
	{
		return getCreatedDateByCM(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedDateByCM
	 */
	public final java.util.Date getCreatedDateByCM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreatedDateByCM.toString());
	}

	/**
	 * Set value of CreatedDateByCM
	 * @param createddatebycm
	 */
	public final void setCreatedDateByCM(java.util.Date createddatebycm)
	{
		setCreatedDateByCM(getContext(), createddatebycm);
	}

	/**
	 * Set value of CreatedDateByCM
	 * @param context
	 * @param createddatebycm
	 */
	public final void setCreatedDateByCM(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date createddatebycm)
	{
		getMendixObject().setValue(context, MemberNames.CreatedDateByCM.toString(), createddatebycm);
	}

	/**
	 * @return value of SentDate
	 */
	public final java.util.Date getSentDate()
	{
		return getSentDate(getContext());
	}

	/**
	 * @param context
	 * @return value of SentDate
	 */
	public final java.util.Date getSentDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.SentDate.toString());
	}

	/**
	 * Set value of SentDate
	 * @param sentdate
	 */
	public final void setSentDate(java.util.Date sentdate)
	{
		setSentDate(getContext(), sentdate);
	}

	/**
	 * Set value of SentDate
	 * @param context
	 * @param sentdate
	 */
	public final void setSentDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date sentdate)
	{
		getMendixObject().setValue(context, MemberNames.SentDate.toString(), sentdate);
	}

	/**
	 * @return value of PhoneNumber
	 */
	public final java.lang.String getPhoneNumber()
	{
		return getPhoneNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of PhoneNumber
	 */
	public final java.lang.String getPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PhoneNumber.toString());
	}

	/**
	 * Set value of PhoneNumber
	 * @param phonenumber
	 */
	public final void setPhoneNumber(java.lang.String phonenumber)
	{
		setPhoneNumber(getContext(), phonenumber);
	}

	/**
	 * Set value of PhoneNumber
	 * @param context
	 * @param phonenumber
	 */
	public final void setPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phonenumber)
	{
		getMendixObject().setValue(context, MemberNames.PhoneNumber.toString(), phonenumber);
	}

	/**
	 * @return value of Reference
	 */
	public final java.lang.String getReference()
	{
		return getReference(getContext());
	}

	/**
	 * @param context
	 * @return value of Reference
	 */
	public final java.lang.String getReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Reference.toString());
	}

	/**
	 * Set value of Reference
	 * @param reference
	 */
	public final void setReference(java.lang.String reference)
	{
		setReference(getContext(), reference);
	}

	/**
	 * Set value of Reference
	 * @param context
	 * @param reference
	 */
	public final void setReference(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reference)
	{
		getMendixObject().setValue(context, MemberNames.Reference.toString(), reference);
	}

	/**
	 * @return value of ErrorMessage
	 */
	public final java.lang.String getErrorMessage()
	{
		return getErrorMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of ErrorMessage
	 */
	public final java.lang.String getErrorMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ErrorMessage.toString());
	}

	/**
	 * Set value of ErrorMessage
	 * @param errormessage
	 */
	public final void setErrorMessage(java.lang.String errormessage)
	{
		setErrorMessage(getContext(), errormessage);
	}

	/**
	 * Set value of ErrorMessage
	 * @param context
	 * @param errormessage
	 */
	public final void setErrorMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String errormessage)
	{
		getMendixObject().setValue(context, MemberNames.ErrorMessage.toString(), errormessage);
	}

	/**
	 * @return value of StatusCode
	 */
	public final java.lang.Integer getStatusCode()
	{
		return getStatusCode(getContext());
	}

	/**
	 * @param context
	 * @return value of StatusCode
	 */
	public final java.lang.Integer getStatusCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.StatusCode.toString());
	}

	/**
	 * Set value of StatusCode
	 * @param statuscode
	 */
	public final void setStatusCode(java.lang.Integer statuscode)
	{
		setStatusCode(getContext(), statuscode);
	}

	/**
	 * Set value of StatusCode
	 * @param context
	 * @param statuscode
	 */
	public final void setStatusCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer statuscode)
	{
		getMendixObject().setValue(context, MemberNames.StatusCode.toString(), statuscode);
	}

	/**
	 * @return value of StatusDescription
	 */
	public final java.lang.String getStatusDescription()
	{
		return getStatusDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of StatusDescription
	 */
	public final java.lang.String getStatusDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StatusDescription.toString());
	}

	/**
	 * Set value of StatusDescription
	 * @param statusdescription
	 */
	public final void setStatusDescription(java.lang.String statusdescription)
	{
		setStatusDescription(getContext(), statusdescription);
	}

	/**
	 * Set value of StatusDescription
	 * @param context
	 * @param statusdescription
	 */
	public final void setStatusDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String statusdescription)
	{
		getMendixObject().setValue(context, MemberNames.StatusDescription.toString(), statusdescription);
	}

	/**
	 * @return value of ExternalStatusDescription
	 */
	public final java.lang.String getExternalStatusDescription()
	{
		return getExternalStatusDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of ExternalStatusDescription
	 */
	public final java.lang.String getExternalStatusDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExternalStatusDescription.toString());
	}

	/**
	 * Set value of ExternalStatusDescription
	 * @param externalstatusdescription
	 */
	public final void setExternalStatusDescription(java.lang.String externalstatusdescription)
	{
		setExternalStatusDescription(getContext(), externalstatusdescription);
	}

	/**
	 * Set value of ExternalStatusDescription
	 * @param context
	 * @param externalstatusdescription
	 */
	public final void setExternalStatusDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String externalstatusdescription)
	{
		getMendixObject().setValue(context, MemberNames.ExternalStatusDescription.toString(), externalstatusdescription);
	}

	/**
	 * @return value of ExternalId
	 */
	public final java.lang.Integer getExternalId()
	{
		return getExternalId(getContext());
	}

	/**
	 * @param context
	 * @return value of ExternalId
	 */
	public final java.lang.Integer getExternalId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ExternalId.toString());
	}

	/**
	 * Set value of ExternalId
	 * @param externalid
	 */
	public final void setExternalId(java.lang.Integer externalid)
	{
		setExternalId(getContext(), externalid);
	}

	/**
	 * Set value of ExternalId
	 * @param context
	 * @param externalid
	 */
	public final void setExternalId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer externalid)
	{
		getMendixObject().setValue(context, MemberNames.ExternalId.toString(), externalid);
	}

	/**
	 * @return value of Operator
	 */
	public final java.lang.String getOperator()
	{
		return getOperator(getContext());
	}

	/**
	 * @param context
	 * @return value of Operator
	 */
	public final java.lang.String getOperator(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Operator.toString());
	}

	/**
	 * Set value of Operator
	 * @param operator
	 */
	public final void setOperator(java.lang.String operator)
	{
		setOperator(getContext(), operator);
	}

	/**
	 * Set value of Operator
	 * @param context
	 * @param operator
	 */
	public final void setOperator(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String operator)
	{
		getMendixObject().setValue(context, MemberNames.Operator.toString(), operator);
	}

	/**
	 * @return value of Recipient
	 */
	public final java.lang.String getRecipient()
	{
		return getRecipient(getContext());
	}

	/**
	 * @param context
	 * @return value of Recipient
	 */
	public final java.lang.String getRecipient(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Recipient.toString());
	}

	/**
	 * Set value of Recipient
	 * @param recipient
	 */
	public final void setRecipient(java.lang.String recipient)
	{
		setRecipient(getContext(), recipient);
	}

	/**
	 * Set value of Recipient
	 * @param context
	 * @param recipient
	 */
	public final void setRecipient(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String recipient)
	{
		getMendixObject().setValue(context, MemberNames.Recipient.toString(), recipient);
	}

	/**
	 * @return value of IsSucces
	 */
	public final java.lang.Boolean getIsSucces()
	{
		return getIsSucces(getContext());
	}

	/**
	 * @param context
	 * @return value of IsSucces
	 */
	public final java.lang.Boolean getIsSucces(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsSucces.toString());
	}

	/**
	 * Set value of IsSucces
	 * @param issucces
	 */
	public final void setIsSucces(java.lang.Boolean issucces)
	{
		setIsSucces(getContext(), issucces);
	}

	/**
	 * Set value of IsSucces
	 * @param context
	 * @param issucces
	 */
	public final void setIsSucces(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean issucces)
	{
		getMendixObject().setValue(context, MemberNames.IsSucces.toString(), issucces);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return statusReportForSMSMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final bulksms.proxies.StatusReportForSMS that = (bulksms.proxies.StatusReportForSMS) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BulkSMS.StatusReportForSMS";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
