// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bulksms.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the BulkSMS module
	public static bulksms.proxies.Message message_Message(IContext context, bulksms.proxies.Message _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Message", _message == null ? null : _message.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("BulkSMS.Message_Message").withParams(params).execute(context);
		return result == null ? null : bulksms.proxies.Message.initialize(context, result);
	}
	public static void pUB_InboundSMS(IContext context, bulksms.proxies.InboundSMS _inboundSMS)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("InboundSMS", _inboundSMS == null ? null : _inboundSMS.getMendixObject());
		Core.microflowCall("BulkSMS.PUB_InboundSMS").withParams(params).execute(context);
	}
	public static void pUB_ReceiveStatusReport(IContext context, bulksms.proxies.Msg _msg)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Msg", _msg == null ? null : _msg.getMendixObject());
		Core.microflowCall("BulkSMS.PUB_ReceiveStatusReport").withParams(params).execute(context);
	}
	public static bulksms.proxies.Request request_Request(IContext context, bulksms.proxies.Request _sMS)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SMS", _sMS == null ? null : _sMS.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("BulkSMS.Request_Request").withParams(params).execute(context);
		return result == null ? null : bulksms.proxies.Request.initialize(context, result);
	}
	public static bulksms.proxies.Response sUB_BulkSMSCaller(IContext context, java.lang.String _name_From, java.lang.String _text, java.lang.String _productToken, java.util.List<bulksms.proxies.Number> _numberList, java.lang.Long _maxMultiPart, java.lang.Long _minMultiPart)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Name_From", _name_From);
		params.put("Text", _text);
		params.put("ProductToken", _productToken);
		java.util.ArrayList<IMendixObject> listparam_numberList = null;
		if (_numberList != null)
		{
			listparam_numberList = new java.util.ArrayList<>();
			for (bulksms.proxies.Number obj : _numberList)
				listparam_numberList.add(obj.getMendixObject());
		}
		params.put("NumberList", listparam_numberList);

		params.put("MaxMultiPart", _maxMultiPart);
		params.put("MinMultiPart", _minMultiPart);
		IMendixObject result = (IMendixObject)Core.microflowCall("BulkSMS.SUB_BulkSMSCaller").withParams(params).execute(context);
		return result == null ? null : bulksms.proxies.Response.initialize(context, result);
	}
	public static bulksms.proxies.Response sUB_SendMultipleSMS(IContext context, java.lang.String _name_From, java.lang.String _text, java.lang.String _productToken, java.util.List<bulksms.proxies.Number> _numberList)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Name_From", _name_From);
		params.put("Text", _text);
		params.put("ProductToken", _productToken);
		java.util.ArrayList<IMendixObject> listparam_numberList = null;
		if (_numberList != null)
		{
			listparam_numberList = new java.util.ArrayList<>();
			for (bulksms.proxies.Number obj : _numberList)
				listparam_numberList.add(obj.getMendixObject());
		}
		params.put("NumberList", listparam_numberList);

		IMendixObject result = (IMendixObject)Core.microflowCall("BulkSMS.SUB_SendMultipleSMS").withParams(params).execute(context);
		return result == null ? null : bulksms.proxies.Response.initialize(context, result);
	}
	public static bulksms.proxies.Response sUB_SendSMS(IContext context, java.lang.String _text, java.lang.String _phoneNumber_To, java.lang.String _productToken, java.lang.String _name_From)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Text", _text);
		params.put("PhoneNumber_To", _phoneNumber_To);
		params.put("ProductToken", _productToken);
		params.put("Name_From", _name_From);
		IMendixObject result = (IMendixObject)Core.microflowCall("BulkSMS.SUB_SendSMS").withParams(params).execute(context);
		return result == null ? null : bulksms.proxies.Response.initialize(context, result);
	}
	public static boolean sUB_ValidateRequest(IContext context, java.lang.String _text, java.lang.String _productToken, java.lang.String _name_From, java.util.List<bulksms.proxies.Number> _numberList, java.lang.Long _maxMultiPart, java.lang.Long _minMultiPart)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Text", _text);
		params.put("ProductToken", _productToken);
		params.put("Name_From", _name_From);
		java.util.ArrayList<IMendixObject> listparam_numberList = null;
		if (_numberList != null)
		{
			listparam_numberList = new java.util.ArrayList<>();
			for (bulksms.proxies.Number obj : _numberList)
				listparam_numberList.add(obj.getMendixObject());
		}
		params.put("NumberList", listparam_numberList);

		params.put("MaxMultiPart", _maxMultiPart);
		params.put("MinMultiPart", _minMultiPart);
		return (java.lang.Boolean) Core.microflowCall("BulkSMS.SUB_ValidateRequest").withParams(params).execute(context);
	}
}