// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bulksms.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the BulkSMS module

	public static java.lang.String getCMLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("BulkSMS.CMLogNode");
	}

	public static java.lang.String getEndpointURL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("BulkSMS.EndpointURL");
	}

	/**
	* Handles the SMS inbound
	*/
	public static java.lang.String getInboundSMSMicroflow()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("BulkSMS.InboundSMSMicroflow");
	}

	public static java.lang.String getProductToken()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("BulkSMS.ProductToken");
	}

	/**
	* Module.MicroflowName
	*/
	public static java.lang.String getStatusReportMicroflow()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("BulkSMS.StatusReportMicroflow");
	}
}